class Autogenerated {
  List<Data>? data;
  Metadata? metadata;

  Autogenerated({this.data, this.metadata});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(new Data.fromJson(v));
      });
    }
    metadata = json['metadata'] != null
        ? new Metadata.fromJson(json['metadata'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    if (this.metadata != null) {
      data['metadata'] = this.metadata!.toJson();
    }
    return data;
  }
}

class Data {
  int? id;
  String? title;
  String? poster;
  String? year;
  String? country;
  String? imdbRating;
  List<String>? genres;
  List<String>? images;

  Data(
      {this.id,
        this.title,
        this.poster,
        this.year,
        this.country,
        this.imdbRating,
        this.genres,
        this.images});

  Data.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    poster = json['poster'];
    year = json['year'];
    country = json['country'];
    imdbRating = json['imdb_rating'];
    genres = json['genres'].cast<String>();
    images = json['images'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    data['poster'] = this.poster;
    data['year'] = this.year;
    data['country'] = this.country;
    data['imdb_rating'] = this.imdbRating;
    data['genres'] = this.genres;
    data['images'] = this.images;
    return data;
  }
}

class Metadata {
  String? currentPage;
  int? perPage;
  int? pageCount;
  int? totalCount;

  Metadata({this.currentPage, this.perPage, this.pageCount, this.totalCount});

  Metadata.fromJson(Map<String, dynamic> json) {
    currentPage = json['current_page'];
    perPage = json['per_page'];
    pageCount = json['page_count'];
    totalCount = json['total_count'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['current_page'] = this.currentPage;
    data['per_page'] = this.perPage;
    data['page_count'] = this.pageCount;
    data['total_count'] = this.totalCount;
    return data;
  }
}